from typing import Final

AUTH_INVALID_CREDENTIALS: Final = "AUTH_INVALID_CREDENTIALS"
AUTH_FORBIDDEN: Final = "AUTH_FORBIDDEN"
SCENARIO_NOT_VALID: Final = "SCENARIO_NOT_VALID"
SESSION_NOT_READY: Final = "SESSION_NOT_READY"
HINT_LIMIT_EXCEEDED: Final = "HINT_LIMIT_EXCEEDED"
VERIFICATION_FAILED: Final = "VERIFICATION_FAILED"
LLM_PROVIDER_UNAVAILABLE: Final = "LLM_PROVIDER_UNAVAILABLE"
SANDBOX_LIMIT_EXCEEDED: Final = "SANDBOX_LIMIT_EXCEEDED"
REPORT_PERIOD_REQUIRED: Final = "REPORT_PERIOD_REQUIRED"
VALIDATION_ERROR: Final = "VALIDATION_ERROR"
NOT_IMPLEMENTED: Final = "NOT_IMPLEMENTED"
